name: Collect Code Coverage for 2024 Python
on: [push]
jobs:
  test:
    name: Run Python tests and collect coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2024
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          coverage run -m pytest
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Python2024
          files: ./2024/coverage.xml
